name: engineer-lab-stack # logical project name (optional)

services:
  engineer-lab:
    build: .
    container_name: engineer-lab-local
    restart: unless-stopped

    # The container exposes port 80; map it to an easy-to-remember host port.
    ports:
      - '8080:80'

    # Health-check keeps `docker compose ps` useful in dev
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --no-verbose --tries=1 --spider http://localhost || exit 1',
        ]
      interval: 30s
      timeout: 3s
      retries: 3

    # Same network name you use in production so container aliases resolve.
    networks: [web]

networks:
  web:
    driver: bridge
